In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output


In [10]:
env = gym.make("FrozenLake-v0")
action_space_size = env.action_space.n
state_space_size = env.observation_space.n

q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [11]:
num_episodes = 20000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

### Q-learning algorithm
```
for episode in range(num_episodes):
    # initialize new episode params
    
    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        # Take new action
        # Update Q-table
        # Set new state
        # Add new reward        

    # Exploration rate decay   
    # Add current episode reward to total rewards list
```

In [12]:
rewards_all_episodes = []
for episode in range(num_episodes):
    state = env.reset()
    done = False
    rewards_current_episode = 0

    for step in range(max_steps_per_episode): 
        # Exploration-exploitation trade-off
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state,:]) 
        else:
            action = env.action_space.sample()
        #take new action
        new_state, reward, done, info = env.step(action)
        # Update Q-table for Q(s,a)
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + \
            learning_rate * (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward 
        
        if done == True: 
            break
            
    # Exploration rate decay
    exploration_rate = min_exploration_rate + \
        (max_exploration_rate - min_exploration_rate) * np.exp(-exploration_decay_rate*episode)
    rewards_all_episodes.append(rewards_current_episode)
    

In [13]:
# Calculate and print the average reward per thousand episodes
rewards_per_thosand_episodes = np.split(np.array(rewards_all_episodes),num_episodes/1000)
count = 1000

print("********Average reward per thousand episodes********\n")
for r in rewards_per_thosand_episodes:
    print(count, ": ", str(sum(r/1000)))
    count += 1000


********Average reward per thousand episodes********

1000 :  0.04100000000000003
2000 :  0.05500000000000004
3000 :  0.08400000000000006
4000 :  0.10800000000000008
5000 :  0.10900000000000008
6000 :  0.1320000000000001
7000 :  0.1460000000000001
8000 :  0.17500000000000013
9000 :  0.24000000000000019
10000 :  0.2620000000000002
11000 :  0.45800000000000035
12000 :  0.6610000000000005
13000 :  0.6670000000000005
14000 :  0.6930000000000005
15000 :  0.6980000000000005
16000 :  0.6840000000000005
17000 :  0.6650000000000005
18000 :  0.7030000000000005
19000 :  0.6820000000000005
20000 :  0.6890000000000005


In [15]:
# Print updated Q-table
print("\n\n********Q-table********\n")
print(q_table)



********Q-table********

[[0.56155668 0.50676359 0.51113332 0.51633663]
 [0.31394613 0.31218741 0.24458661 0.49321051]
 [0.41637602 0.37275899 0.41689343 0.45542588]
 [0.20679537 0.29910297 0.36394872 0.42988882]
 [0.58086203 0.41773475 0.44126002 0.42910216]
 [0.         0.         0.         0.        ]
 [0.33825872 0.14911566 0.18237918 0.0651859 ]
 [0.         0.         0.         0.        ]
 [0.33209066 0.48196698 0.49282896 0.64355292]
 [0.2918537  0.70621805 0.53639371 0.44925847]
 [0.65793949 0.41190176 0.40708876 0.33627327]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.4509215  0.62594686 0.76507311 0.51494189]
 [0.74501853 0.84665135 0.77416626 0.77714155]
 [0.         0.         0.         0.        ]]


### The code to watch the agent play the game 
```
# Watch our agent play Frozen Lake by playing the best action 
# from each state according to the Q-table

for episode in range(3):
    # initialize new episode params

    for step in range(max_steps_per_episode):        
        # Show current state of environment on screen
        # Choose action with highest Q-value for current state       
        # Take new action
        
        if done:
            if reward == 1:
                # Agent reached the goal and won episode
            else:
                # Agent stepped in a hole and lost episode            
            
        # Set new state
        
env.close()
```



In [16]:
for episode in range(3):
    state = env.reset()
    done = False
    print("*****EPISODE ", episode+1, "*****\n\n\n\n")
    time.sleep(1)
    
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)
        
        action = np.argmax(q_table[state,:])        
        new_state, reward, done, info = env.step(action)
        
        if done:
            clear_output(wait=True)
            env.render()
            if reward == 1:
                print("****You reached the goal!****")
                time.sleep(3)
            else:
                print("****You fell through a hole!****")
                time.sleep(3)
                clear_output(wait=True)
            break
        state = new_state

env.close()

  (Down)
SFFF
FHFH
FFFH
HFFG
****You reached the goal!****
